### ISSUE TITLE
现在npm是否支持使用echart3?

### ISSUE THREAD

**Issue by kyhwsk** [luqin/echarts#16]
rt， 看到例子中依赖的还是echart2.x呢，而且直接按照npm中说明文档也无法使用

**Comment by luqin** [comment]
示例：
echarts2：https://github.com/luqin/echarts-webpack-starter-kit
echarts3：https://github.com/luqin/echarts-webpack-starter-kit/tree/echarts-3

这个例子不好使吗？公司的项目运行一切正常呢，能否贴出具体错误信息。

**Comment by kyhwsk** [comment]
已解决，原来是因为先前没注意到你的echart3分支，非常感谢作者~

**Comment by luqin** [comment]
解决了就好 :smile:
